---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- ./00_operator
  #- ./01_kube_prom_setup
  - ./02_kube_prom
  - http_route.yaml
  - grafana-dashboardDefinitions-dns.yaml
patches:
  - path: grafana-deployment-patch.yaml
