bootstrapPassword: <PASSWORD>
hostname: rancher.local.julianmaze.com
replicas: 1
privateCA: false
ingress.enabled: true
ingress.tls.source: secret # I want this to point to the ingress
ingress.extraAnnotations:
  cert-manager.io/cluster-issuer: cloudflare-jmaze # This takes care of the TLS cert
  kubernetes.io/ingress.class: nginx # This takes care of the ip assignment
livenessProbe:
  initialDelaySeconds: 180
  periodSeconds: 90
readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 90
# As of 4/24/26 v2.13.3 is the latest stable release
# WARNING: UPGRADE EVERY MINOR VERSION. v2.10.3 >> v2.11.0 >> v2.12.0 >> v2.13.3
#     v2.10.3 >> v2.13.3 is NOT a valid upgrade path
# helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
# helm repo update
# helm search repo rancher-stable -l
# helm upgrade rancher rancher-stable/rancher --namespace cattle-system -f values.yaml --version 2.13.3
# or
# helm upgrade rancher rancher-stable/rancher --namespace cattle-system --reuse-values
